---
title: "Writeup mvordnorm"
output: pdf_document
header-includes:
  - \usepackage{bm}
---

# Model

We propose a joint model of continuous and ordinal variables. Let's assume we 
have $q_n$ continuous responses and $q_o$ ordinal responses (in total $q=q_n+q_o$).

For the continuous variables $\boldsymbol y^n_{1},\ldots, \boldsymbol y^n_{q_n}$  have 
$$
y^n_{ij} = \beta_{0j} + \beta_j^\top x_i + \sigma_j \epsilon^n_{ij}
$$
For the ordinal variables  $\boldsymbol y^o_{1},\ldots, \boldsymbol y^o_{q_o}$ have 
$$
\tilde y^o_{ij} = \beta_j^\top x_i + \epsilon^o_{ij}
$$
$$
y^o_{ij} = r \Rightarrow \theta_{j, r-1}\leq \tilde y^o_{ij}\leq \theta_{j, r}
$$
The jointness is captured by assuming that the continuous and the latent variables
of the ordinals come from a multivariate normal distribution:
$$
(\boldsymbol\epsilon^o_{i}, \boldsymbol\epsilon^n_{ij})^\top \sim N(0, R)
$$

# Pairwise likelihood

Assume we collect all $q$ responses in a matrix $Y$.
The pairwise likelihood is given by:

$$
p\ell(\Theta; Y, X) =\sum_{i=1}^n \sum_{k,l} f(y_{ik}, y_{il})
$$


We have three cases:

* both responses are ordinal

* both responses are normal

* one response is ordinal, one normal


## Both responses are ordinal

$$
f(y_{ik}, y_{il}) = Pr(y_{ik}=r_{ik}, y_{il} = r_{il}) = \int_{\theta_{k, r_{ik}-1}}^{\theta_{k, r_{ik}}} \phi_2(\tilde y_{ik} - \beta_k^\top x_i, \tilde y_{il} - \beta_k^\top x_i; \rho_{kl}) d\tilde y_{ik}d\tilde y_{il} = 
$$
Let's denote by 
$U_k = \theta_{k, r_{ik}} - \beta_k^\top x_i$ ,
$L_k = \theta_{k, r_{ik}-1} - \beta_k^\top x_i$,
$U_l = \theta_{k, r_{il}} - \beta_l^\top x_i$,
$L_l = \theta_{k, r_{ik}-1} - \beta_l^\top x_i$. We then have the rectangular probability:
$$
=\Phi_2\left(U_k, U_l;  \rho_{kl} \right)-\Phi_2\left(L_k, U_l;  \rho_{kl} \right)-\Phi_2\left(U_k, L_l;  \rho_{kl} \right)
+\Phi_2\left(L_k, L_l;  \rho_{kl} \right)
$$
where $\rho_{kl}$ is the correlation coefficient between responses $k$ and $l$ and $\phi_2$ is
the bivariate standard normal pdf and $\Phi_2$ is the bivariate standard normal cdf .

## Both responses are continuous.

$$
f(y_{ik}, y_{il}) = \phi_2\left(\frac{y_{ik} - \beta_{0k} -\beta_k^\top x_i}{\sigma_k}, \frac{y_{il} - \beta_{0l} -\beta_l^\top x_i}{\sigma_l}; \rho_{kl}) \right)
$$

## One response is ordinal, one continuous.

Slightly abusing notation we assume the $k$th response is ordinal and the $l$ th 
is continuous.
$$
f(y^o_{ik}, y^n_{il}) = f(y^o_{ik} | y^n_{il})f(y^n_{il})
$$
where $f(y^n_{il})$ is the marginal standard normal pdf $\phi\left(\frac{y^n_{il} - \beta_{0l} -\beta_l^\top x_i}{\sigma_l} \right)$. 
The conditional term is:
$$
f(y^o_{ik} | y^n_{il}) = Pr(y^o_{ik}=r_{ik} | y^n_{il}) = Pr(\theta_{k, r_{ik}-1}\leq \tilde y^o_{ik}\leq \theta_{k, r_{ik}} | y^n_{il})
$$

Given that $\tilde y^o_{ik}$ and $y^n_{il}$ are bivariate normals we have:

$$
\tilde y^o_{ik} | y^n_{il} \sim N\left(\underbrace{\beta_k^\top x_i + \frac{\rho_{kl}}{\sigma_l}(y^n_{il} - \beta_{0l} -\beta_l^\top x_i)}_{\mu_c}, \underbrace{(1 - \rho_{kl}^2)}_{\sigma_c^2}\right)
$$
So
$$
f(y^o_{ik} | y^n_{il}) = Pr(\theta_{k, r_{ik}-1}\leq \tilde y^o_{ik}\leq \theta_{k, r_{ik}} | y^n_{il})=
\int_{\theta_{k, r_{ik}-1}}^{\theta_{k, r_{ik}}} \phi\left(\frac{\tilde y^o_{ik} - \mu_c}{\sigma_c}\right) d\tilde y^o_{ik} = 
\Phi\left(\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c}\right)-\Phi\left(\frac{\theta_{k, r_{ik}-1} - \mu_c}{\sigma_c}\right)
$$


# Standard errors

## Univariate case

If for some observations only one response $j$ is observed, then we have two cases: either an ordinal response, or a continuous response.


### Ordinal response 
The negative log-likelihood is:
$$
\textrm{neglog}\mathcal L^j_{i} = -\log\left(\Phi\left( \theta_{j, r_{ij}} - \boldsymbol \beta_j^\top \boldsymbol x_i\right)-\Phi\left( \theta_{j, r_{ij}-1} - \boldsymbol \beta_j^\top \boldsymbol x_i\right)\right)
$$
Assume $\tilde x^u_i = (0,1,..,-\boldsymbol x_i)^\top$ and $\tilde x^l_i = (1,0,..,-x_i)^\top$ (i.e., we make a dummy matrix of dimension $K_j$ where for the lower predictors we eliminate the first column and for the upper predictors we eliminate the last column) and $\boldsymbol \psi_j=(\boldsymbol \theta_j, \boldsymbol \beta_j)^\top$. The relevant derivatives are:

$$
\frac{\partial\textrm{neglog}\mathcal L^j_{i}}{\boldsymbol \psi_j}=-\frac{1}{\Phi\left( \psi_j^\top \tilde x^u_i\right)-\Phi\left(\psi_j^\top \tilde x^l_i\right)}(\phi(\psi_j^\top \tilde x^u_i)\tilde x^u_i - \phi(\psi_j^\top \tilde x^l_i)\tilde x^l_i)
$$

### Gaussian responses

The negative log-likelihood is:
$$
\textrm{neglog}\mathcal L^j_{i} = -\log\left(\frac{1}{\sqrt{2\pi\sigma^2_j}}\exp\left(-\frac{(y_i - \beta_{j}^{*\top} x^*_i)^2}{2\sigma_j^2}\right)\right) = 0.5\log(2\pi)+\log(\sigma_j) + \frac{(y_i - \beta_{j}^{*\top} x^*_i)^2}{2\sigma_j^2}
$$
where $x^*_i=(1, x_i)^\top$ and $\beta^*_{j}=(\beta_{0j}, \bm\beta_j)^\top$.


The relevant derivatives are:

$$
\frac{\partial\textrm{neglog}\mathcal L^j_{i}}{\boldsymbol \beta^*_{j}}=-x^*_i\frac{(y_i - \beta_{j}^{*\top} x^*_i)}{\sigma_j^2}
$$
$$
\frac{\partial\textrm{neglog}\mathcal L^j_{i}}{\sigma_{j}}=\frac{1}{\sigma_j} +
\frac{(y_i - \beta_{j}^{*\top} x^*_i)^2}{2}\cdot (-2)\sigma_j^{-3} = 
\frac{1}{\sigma_j} -
(y_i - \beta_{j}^{*\top} x^*_i)^2\cdot \sigma_j^{-3}
$$

## Bivariate case

### Case 1: 2 ordinal variables

See derivations for **mvord**. In principle we have:


$$
\textrm{neglog}\mathcal L^{k,l}_{i} = -\log\left(\Phi_2(U_k, U_l,\rho) - \Phi_2(U_k, L_l,\rho) -\Phi_2(U_l, L_k,\rho)+\Phi_2(L_k, L_l,\rho) \right)
$$
where
$U_k = \psi_k^\top \tilde x^u_i$,
$L_k = \psi_k^\top \tilde x^l_i$,
$U_l = \psi_l^\top \tilde x^u_i$,
$L_l =\psi_l^\top \tilde x^l_i$. 

Let $p^{k,l} = \Phi_2(U_k, U_l,\rho) - \Phi_2(U_k, L_l,\rho) -\Phi_2(U_l, L_k,\rho)+\Phi_2(L_k, L_l,\rho)$. 


We use here the property that:
$$
\frac{\partial\Phi_2(x, y, \rho)}{\partial x} = \phi(x)\Phi\left(\frac{y - \rho x}{\sqrt{1-\rho^2}}\right)
$$
and 
$$
\frac{\partial\Phi_2(x, y, \rho)}{\partial \rho} = \frac{1}{2\pi\sqrt{1-\rho^2}}
\exp\left(\frac{-x^2 - 2\rho xy + y^2}{2(1-\rho^2)}\right)
$$

The relevant derivatives are:
\begin{align*}
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{\boldsymbol \psi_k}&=-\frac{1}{p^{k,l}}\left(\frac{\partial\Phi_2(U_k,U_l,\rho)}{\partial U_k}\cdot \tilde x^u_i - \frac{\partial\Phi_2(U_k,L_l,\rho)}{\partial U_k}\cdot \tilde x^u_i - \frac{\partial\Phi_2(U_l,L_k,\rho)}{\partial L_k}\cdot \tilde x^l_i + \frac{\partial\Phi_2(L_l,L_k,\rho)}{\partial L_k}\cdot \tilde x^l_i\right)\\
&=-\frac{1}{p^{k,l}}\left(\left(\frac{\partial\Phi_2(U_k,U_l,\rho)}{\partial U_k} - \frac{\partial\Phi_2(U_k,L_l,\rho)}{\partial U_k}\right)\cdot \tilde x^u_i -  \left(\frac{\partial\Phi_2(U_l,L_k,\rho)}{\partial L_k}\right) - \frac{\partial\Phi_2(L_l,L_k,\rho)}{\partial L_k}\cdot \tilde x^l_i\right)\\
\end{align*}


\begin{align*}
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{\boldsymbol \psi_l}&=-\frac{1}{p^{k,l}}\left(\frac{\partial\Phi_2(U_k,U_l,\rho)}{\partial U_l}\cdot \tilde x^u_i - \frac{\partial\Phi_2(U_k,L_l,\rho)}{\partial L_l}\cdot \tilde x^l_i - \frac{\partial\Phi_2(U_l,L_k,\rho)}{\partial U_l}\cdot \tilde x^u_i + \frac{\partial\Phi_2(L_l,L_k,\rho)}{\partial L_l}\cdot \tilde x^l_i\right)\\
&=-\frac{1}{p^{k,l}}\left(\left(\frac{\partial\Phi_2(U_k,U_l,\rho)}{\partial U_l} - \frac{\partial\Phi_2(U_l,L_k,\rho)}{\partial U_l}\right)\cdot \tilde x^u_i -  \left(\frac{\partial\Phi_2(U_k,L_l,\rho)}{\partial L_l}\right) - \frac{\partial\Phi_2(L_l,L_k,\rho)}{\partial L_l}\cdot \tilde x^l_i\right)\\
\end{align*}

\begin{align*}
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{ \rho}&=-\frac{1}{p^{k,l}}\left(\frac{\partial\Phi_2(U_k,U_l,\rho)}{\partial \rho} - \frac{\partial\Phi_2(U_k,L_l,\rho)}{\partial \rho} - \frac{\partial\Phi_2(U_l,L_k,\rho)}{\partial \rho} + \frac{\partial\Phi_2(L_l,L_k,\rho)}{\partial \rho}\right)
\end{align*}

### Case 2: Bivariate Gaussian 

The bivariate negative log likelihood in this case is:

$$
\textrm{neglog}\mathcal L^{k,l}_{i} \propto 0.5\log(\det(\Sigma)) + \frac{1}{2}(\bm y_i - \bm\mu)^\top\Sigma^{-1}(\bm y_i - \bm\mu)
$$
where $\bm\mu = (\beta^{*\top}_kx^*_i, \beta^{*\top}_lx^*_i)$ and $\Sigma=\begin{pmatrix}\sigma^2_k & \sigma_k\sigma_l\rho \\\sigma_k\sigma_l\rho & \sigma^2_k\end{pmatrix}$.

We use (see https://stats.stackexchange.com/questions/27436/how-to-take-derivative-of-multivariate-normal-density)
$$
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{\partial\mu} = -\Sigma^{-1}(\bm y_i-\bm\mu)
$$
and 
$$
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{\partial\Sigma} = 
\frac{1}{2}(2\Sigma^{-1} - (\Sigma^{-1} \circ I) - 2\Sigma^{-1}(\bm y_i - \bm\mu)(\bm y_i - \bm\mu)^\top\Sigma^{-1} + (\Sigma^{-1}(\bm y_i - \bm\mu)(\bm y_i - \bm\mu)^\top\Sigma^{-1}\circ I)
$$
where $\circ$ denotes the Hadamard product (elementwise product). The last expression is based on the following:
$$
\frac{\partial\log(\det(\Sigma))}{\partial\Sigma} = 2\Sigma^{-1} - (\Sigma^{-1} \circ I)
$$
and 
$$
\frac{\partial\mathrm{trace}(\Sigma^{-1}xx^\top)}{\partial\Sigma} = - 2\Sigma^{-1}xx^\top\Sigma^{-1} + (\Sigma^{-1}xx^\top\Sigma^{-1}\circ I)
$$
The relevant derivatives are:
$$
\frac{\partial\textrm{neglog}\mathcal L^{k,l}_{i}}{\partial B^*_{kl}} =  
2\bm x^*_i \bm y_i^\top \Sigma^{-1} - 2 \bm x^*_i \bm x_i^{*\top} B^*_{kl}\Sigma^{-1}
$$
where $B^*_{kl}$ is a $(p \times 2)$ matrix where the first column contains $\beta^*_k$ and second one contains $\beta^*_l$. (see slide 60 http://users.stat.umn.edu/~helwig/notes/mvlr-Notes.pdf)

We can then use a numeric Jacobian to compute $\partial\Sigma/\partial\rho$,
$\partial\Sigma/\partial\sigma_k$, $\partial\Sigma/\partial\sigma_l$ (can be done easily by hand if time is no constraint).

### Case 3: Mixture of Gaussian and ordinal

If we have 1 normal variable at position $l$ and one ordinal variable at position $k$ we have:
$$
\textrm{neglog}\mathcal L^{k,l}_{i} = \log\left(\Phi(\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c}) - \Phi(\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c})\right) + 0.5\log(2\pi)+\log(\sigma_l) + \frac{(y_{il} - \beta_{l}^{*\top} x^*_i)^2}{2\sigma_l^2}
$$


Let $\eta^u_c=\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c}$ and 
 $\eta^l_c=\frac{\theta_{k, r_{ik}-1} - \mu_c}{\sigma_c}$.
Let $p^{k,l}_c = \Phi(\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c}) - \Phi(\frac{\theta_{k, r_{ik}} - \mu_c}{\sigma_c})$.

The relevant derivatives are:

$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \bm\psi_k} = - \frac{1}{p^{k,l}_c} \left(\phi(\eta^u_c) \frac{\partial\eta^u_c}{\partial \bm\psi_k} - \phi(\eta^l_c) \frac{\partial\eta^l_c}{\partial \bm\psi_k}\right)
$$
Given that
$$
\eta^u_c = \frac{\psi_k^\top \tilde x^u_i - \frac{\rho}{\sigma_l}(y_{il}-\beta^{*\top}_lx^*_i)}{\sqrt{1-\rho^2}}
$$
we have
$$
\frac{\partial\eta^u_c}{\partial \bm\psi_k} = \frac{1}{\sqrt{1-\rho^2}}\tilde x^u_i.
$$
Similarly, 
$$
\frac{\partial\eta^l_c}{\partial \bm\psi_k} = \frac{1}{\sqrt{1-\rho^2}}\tilde x^l_i.
$$
Putting it all together:
$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \bm\psi_k} = - \frac{1}{p^{k,l}_c} \left(\phi(\eta^u_c) \frac{1}{\sqrt{1-\rho^2}}\tilde x^u_i - \phi(\eta^l_c) \frac{1}{\sqrt{1-\rho^2}}\tilde x^l_i\right).
$$
Now for the coefficients of the normal variable $\beta^*_l$
$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \bm\beta^*_l} = - \frac{1}{p^{k,l}_c}\left(\phi(\eta^u_c) \frac{\partial\eta^u_c}{\partial \bm\beta^*_l} - \phi(\eta^l_c) \frac{\partial\eta^l_c}{\partial \bm\beta^*_l}\right) -x^*_i
\frac{(y_{il} - \beta^{*\top}_l x^*_i)}{\sigma_l^2}
$$
where we have
$$
\frac{\partial\eta^u_c}{\partial \bm\beta^*_l} = \frac{\partial\eta^l_c}{\partial \bm\beta^*_l} =
\frac{\rho}{\sigma_l\sqrt{1-\rho^2}}x^*_i.
$$

Putting it all together:

$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \bm\beta^*_l} = - \frac{1}{p^{k,l}_c}\frac{\rho}{\sigma_l\sqrt{1-\rho^2}}x^*_i\left(\phi(\eta^u_c)  - \phi(\eta^l_c) \right) -x^*_i
\frac{(y_{il} - \beta^{*\top}_l x^*_i)}{\sigma_l^2}
$$
For the correlation parameter of the pair:
$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \rho} = -\frac{1}{p^{k,l}_c} \left(\phi(\eta^u_c) \frac{\partial\eta^u_c}{\partial \rho} -\phi(\eta^l_c)\frac{\partial\eta^l_c}{\partial \rho}\right)
$$
where let $g^u(\rho)=\psi_k^\top \tilde x^u_i - \frac{\rho}{\sigma_l}(y_{il}-\beta^{*\top}_lx^*_i)$ and $h(\rho)=\sqrt{1-\rho^2}$, $\partial h(\rho)/\partial \rho = - \rho/\sqrt{1-\rho^2}$.

$$
\frac{\partial\eta^u_c}{\partial \rho} =\frac{(\sqrt{1-\rho^2})
 (y_{il} - \beta_l^{*\top} x^*_i)/\sigma_l + \rho/\sqrt{1-\rho^2}\cdot g^u(\rho)}{1-\rho^2}=\frac{(y_{il} - \beta_l^{*\top} x^*_i)/\sigma_l}{\sqrt{1-\rho^2}} + \frac{\rho \eta^u_c}{1-\rho^2}
$$
and 
$$
\frac{\partial\eta^l_c}{\partial \rho} =\frac{(y_{il} - \beta_l^{*\top} x^*_i)/\sigma_l}{\sqrt{1-\rho^2}} + \frac{\rho \eta^l_c}{1-\rho^2}
$$

Finally, for the standard deviation parameter of the normal:
$$
\frac{\partial \textrm{neglog}\mathcal L^{k,l}_{i}}{\partial \sigma_l} = -\frac{1}{p^{k,l}_c} \left(\phi(\eta^u_c) \frac{\partial\eta^u_c}{\partial \sigma_l} -\phi(\eta^l_c)\frac{\partial\eta^l_c}{\partial \sigma_l}\right) +
\frac{1}{\sigma_l} -
(y_{il} - \beta_{l}^{*\top} x^*_i)^2\cdot \sigma_l^{-3}
$$



$$
\frac{\partial\eta^u_c}{\partial\sigma_l} =\frac{\partial\eta^l_c}{\partial\sigma_l} 
=\frac{\rho \sigma_l^{-2}(y_{il} - \beta_{l}^{*\top} x^*_i)}{\sigma_c}
$$

